# Generated by Django 6.0.3 on 2026-04-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rasa',
            new_name='Race',
        ),
    ]
